name: flutter_offers
description: Offers.
version: 1.0.0+1

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # ui
  flutter_staggered_grid_view: ^0.3.0
  flutter_rating_bar: ^1.1.0
  expandable: ^4.1.2
  flutter_slidable: ^0.5.4
  image_picker: ^0.6.4
  # firebase
  firebase_auth: ^0.15.5+3
  cloud_firestore: ^0.13.4+2
  # state management
  provider: ^4.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  fonts:
    - family: GoogleSans
      fonts:
        - asset: assets/fonts/GoogleSans-Regular.ttf
        - asset: assets/fonts/GoogleSans-Bold.ttf
        - asset: assets/fonts/GoogleSans-Italic.ttf
        - asset: assets/fonts/GoogleSans-Medium.ttf
        - asset: assets/fonts/GoogleSans-BoldItalic.ttf
        - asset: assets/fonts/GoogleSans-MediumItalic.ttf

  assets:
    - assets/images/
    - assets/images/logos/
    - assets/images/offers/